# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'


tasks:
  upgrade:
    cmds:
      - helm upgrade openclaw ./openclaw -n openclaw -f openclaw/values.yaml
  rollout:
    cmds:
      - kubectl rollout restart deployment/openclaw-oc-dashboard -n openclaw
